server:
  port: 8901
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  application:
    name: my-gateway
  cloud:
    gateway:
      default-filters[0]: DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials,RETAIN_FIRST
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"